version: "3.8"
services:
  db:
    image: postgres:13
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=postgres
    # volumes:
    #   - pgdata:/var/lib/postgresql/data
